[package]
name = "golem"
description = "Orchestration framework"
authors = ["BorisZhguchev <zhguchev@hotmail.com>"]
homepage = "https://github.com/besok/golem"
repository = "https://github.com/besok/golem"
version = "0.1.0"
edition = "2021"


[dependencies]
parsit = { path = "../parseit" }
logos = "0.13.0"