[package]
name = "forester"
description = "Workflow framework based on the behaviour trees"
authors = ["BorisZhguchev <zhguchev@hotmail.com>"]
homepage = "https://github.com/besok/forester"
repository = "https://github.com/besok/forester"
version = "0.1.0"
edition = "2021"


[dependencies]
parsit = { path = "../parseit" }
graphviz-rust = "0.6.2"
logos = "0.13.0"
itertools = "0.10.5"
strum = "0.24.1"
strum_macros = "0.24.1"
log = "0.4"
env_logger = "0.10.0"
serde = { version = "1.0.166", features = ["derive"] }
serde_json = { version = "1.0.99"}
serde_yaml = "0.9.22"
reqwest = { version = "0.11", features = ["blocking", "json"] }