[package]
name = "forester"
description = "Workflow framework based on the behaviour trees"
authors = ["BorisZhguchev <zhguchev@hotmail.com>"]
homepage = "https://github.com/besok/forester"
repository = "https://github.com/besok/forester"
version = "0.1.0"
edition = "2021"


[dependencies]
parsit = { path = "../parseit" }
graphviz-rust = "0.6.2"
logos = "0.13.0"
itertools = "0.10.5"
serde = "1.0.163"
strum = "0.24.1"
strum_macros = "0.24.1"

tracing = "0.1"