[book]
authors = ["Boris Zhguchev"]
language = "en"
multilingual = false
src = "src"
title = "Documentation"


[output.html]
additional-js = ["mermaid-init.js", "mermaid.min.js", "theme/custom-highlight.js",  ]

[preprocessor.graphviz]
command = "mdbook-graphviz"
output-to-file = false

[preprocessor.mermaid]
command = "mdbook-mermaid"