[book]
authors = ["Boris Zhguchev"]
language = "en"
multilingual = false
src = "src"
title = "Documentation"


[preprocessor.graphviz]
command = "mdbook-graphviz"
output-to-file = false

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["theme/custom-highlight.js", "mermaid.min.js", "mermaid-init.js"]
